"""Detached local worker; accepts only arguments generated by the dashboard."""
from __future__ import annotations

import argparse
import fcntl
import hashlib
import os
from pathlib import Path

from .jobs import RUN_ID, atomic_json, read_json, utc_now


def execute(workspace, run_id, lock_fd):
    if not RUN_ID.fullmatch(run_id):
        raise ValueError("Invalid run identifier")
    # This descriptor was locked before the process was launched. The inherited
    # open-file description preserves single-run ownership across server restarts.
    os.fstat(lock_fd)
    fcntl.flock(lock_fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    root = Path(workspace).resolve()
    path = root / "evidence_dashboard/runtime/jobs" / (run_id + ".json")
    job = read_json(path)
    if job.get("run_id") != run_id or job.get("status") != "QUEUED":
        raise ValueError("Missing queued job")
    job.update(status="RUNNING", pid=os.getpid())
    atomic_json(path, job)
    source = root / "data_cleaning_agent/runtime/enrichment_verification_2026-09-19.json"
    if job.get("source_registry"):
        source = Path(job["source_registry"])
    args = ["--run-id", run_id, "--source-registry", str(source),
            "--output", str(root / "evidence_engine/output"), "--min-support", str(job["min_support"]),
            "--max-conditions", str(job["max_conditions"])]
    if job.get("discovery_end"):
        args += ["--discovery-end", job["discovery_end"]]
    if job.get("resume"):
        args.append("--resume")
    if job.get("publish_to_s3"):
        args += ["--s3-bucket", "heremesv0-cleaned-data", "--s3-prefix", "evidence-engine"]
    try:
        if job.get("source_registry"):
            expected_source = root / "evidence_dashboard/runtime/sources" / (run_id + ".json")
            if source != expected_source or any(part.is_symlink() for part in (source, source.parent, source.parent.parent)):
                raise ValueError("Job source snapshot must use its fixed local path")
            # Resumes exclusively use the engine's saved snapshot and request.
            # They remain resumable even if the dashboard source file is gone.
            if not job.get("resume"):
                if hashlib.sha256(source.read_bytes()).hexdigest() != job.get("source_registry_sha256"):
                    raise ValueError("Job source snapshot changed before execution")
        from evidence_engine.__main__ import main
        code = main(args)
        manifest = read_json(root / "evidence_engine/output/runs" / run_id / "manifest.json")
        if code == 0 and manifest.get("status") == "REGISTERED":
            job.update(status="SUCCEEDED", message="Research complete; integrity checks passed.", error=None)
        elif code == 2 and manifest.get("qa_status") == "INSUFFICIENT_DATA":
            job.update(status="INSUFFICIENT_DATA", message="Research finished with insufficient evidence.", error=None)
        else:
            job.update(status="FAILED", message="Research finished without an integrity pass.",
                       error="Review the saved QA findings before starting a new run.")
    except Exception as exc:
        # Never send exception text, environment variables or provider payloads
        # to the browser or job state. Preserve only the error class for diagnosis.
        manifest = read_json(root / "evidence_engine/output/runs" / run_id / "manifest.json")
        if manifest.get("qa_status") == "INSUFFICIENT_DATA":
            job.update(status="INSUFFICIENT_DATA", message="Research finished with insufficient evidence; S3 publication was skipped.", error=None)
            code = 2
        elif manifest.get("qa_status") == "FAIL":
            job.update(status="FAILED", message="Research finished without an integrity pass; S3 publication was skipped.",
                       error="Review the saved QA findings before starting a new run.")
            code = 2
        elif manifest.get("status") == "REGISTERED" and job.get("publish_to_s3"):
            job.update(status="FAILED", message="Research completed; S3 publication did not finish.",
                       error="Resume this run to retry publication.", error_type=type(exc).__name__)
            code = 1
        else:
            job.update(status="FAILED", message="Research could not finish.",
                       error="Run interrupted or execution failed. Resume if the saved engine version is unchanged.",
                       error_type=type(exc).__name__)
            code = 1
    finally:
        job["finished_at"] = utc_now()
        atomic_json(path, job)
        os.close(lock_fd)
    return code


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--workspace", type=Path, required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--lock-fd", type=int, required=True)
    args = parser.parse_args(argv)
    return execute(args.workspace, args.run_id, args.lock_fd)


if __name__ == "__main__":
    raise SystemExit(main())
